image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:

  - java -jar ./artifacts/app-order.jar
  - gradlew test -Dselenide.headless=true


build_script:
  - ./gradlew test --info
